### ISSUE TITLE
"You" should be "your" in Facilitate Inclusively section.

### ISSUE THREAD

**Issue by Chaitanyassr** [inclusive-design/guide.inclusivedesign.ca#32]
You should be your within <strong>practice</strong> in Facilitate Inclusively section. 
It is present in the third point of "try"
- page link - https://guide.inclusivedesign.ca/practices/FacilitateInclusively.html
![Screenshot (243)](https://user-images.githubusercontent.com/30374226/79055325-de3a6280-7c69-11ea-9bdb-b83e1f2a03c9.png)

**Comment by gmanas813** [comment]
I want to work on this.
