### ISSUE TITLE
"specic" should be "specific".

### ISSUE THREAD

**Issue by Chaitanyassr** [inclusive-design/guide.inclusivedesign.ca#34]
within "tools" in "use case" and inside of try section.
- page link - https://guide.inclusivedesign.ca/tools/UseCases.html
![Screenshot (244)](https://user-images.githubusercontent.com/30374226/79055513-581f1b80-7c6b-11ea-8354-691371b17e9e.png)

**Comment by gmanas813** [comment]
I want to work on this

**Comment by Chayank-Das** [comment]
The word "specic" is just an typo,so it need to correct by simply editing the the word with "specific".I want to work on it.

**Comment by Chayank-Das** [comment]
![Annotation 2020-07-13 105120](https://user-images.githubusercontent.com/67795717/87273583-267e5080-c4f7-11ea-8bf9-3d13276816ab.png)
![Annotation 2020-07-13 105041](https://user-images.githubusercontent.com/67795717/87273585-28481400-c4f7-11ea-948a-3928d39ec867.png)
.
.
.
.
.
.
This "specic" word just need to be edited in html to "specific". It is just a typo. i want to work on this.
