### ISSUE TITLE
"exerise" should be "exercise"

### ISSUE THREAD

**Issue by Chaitanyassr** [inclusive-design/guide.inclusivedesign.ca#35]
In "Activities" under "Cause and effect"
page link - https://guide.inclusivedesign.ca/activities/CauseAndEffect.html

**Comment by creatorpiyush** [comment]
Can I help in this issue is no one is working?

**Comment by Chaitanyassr** [comment]
Hi @creatorpiyush , a PR has already been submitted for this.

**Comment by gmanas813** [comment]
can i work on it?
