### ISSUE TITLE
Mismatch is not alligned properly.

### ISSUE THREAD

**Issue by Chaitanyassr** [inclusive-design/guide.inclusivedesign.ca#37]
## Describe the bug
Mismatch(in activities in why section) is not alligned properly in mobile screen with disability.

## Screenshots
![7275e194-6617-4ac0-861f-88223954570b](https://user-images.githubusercontent.com/30374226/80370964-bd4f4f80-88ae-11ea-8aed-62f4ffa6abd0.jpg)

### Smartphone / tablet 
 - OS: [e.g. andorid 6.1]

**Comment by creatorpiyush** [comment]
Can I help in this issue is no one is working?

**Comment by Chaitanyassr** [comment]
Yes, go ahead.

**Comment by creatorpiyush** [comment]
Take a look @Chaitanyassr

**Comment by Chaitanyassr** [comment]
Hi @creatorpiyush , there is a PR already exist for #35 #34 #32 . So no need of that. A PR can be made for #38 .

**Comment by creatorpiyush** [comment]
so check for this

**Comment by creatorpiyush** [comment]
@Chaitanyassr
