### ISSUE TITLE
UI Options panel should occupy 100% width of the client

### ISSUE THREAD

**Issue by jhung** [inclusive-design/guide.inclusivedesign.ca#66]
## Describe the bug
Currently the UIO panel is restricted to the width of the content area of the Guide site. It would be better to take advantage of the full width of the browser window if possible. 

Originally filed as [FLOE-513](https://issues.fluidproject.org/browse/FLOE-513)

### To reproduce
1. Go to https://guide.inclusivedesign.ca/practices/collaborate
2. Expand the UI Options panel
3. Resize window past 80rem
4. Notice how UIO stays within the 80rem max.

## Screenshots
![image](https://user-images.githubusercontent.com/564762/129628310-feb6d866-ba9a-40b5-80b4-9910fb0f7e37.png)

Screenshot of UIO stuck within the 80rem width.

## Additional context or notes

A solution would be to add a new parent container to `docs-template-container` and move UIO that new parent container.

**Comment by jobara** [comment]
Likely to be addressed with styling changes need for #54
