### ISSUE TITLE
It's not obvious how to navigate back to the home/intro page of Design Guide

### ISSUE THREAD

**Issue by jhung** [inclusive-design/guide.inclusivedesign.ca#68]
## Describe the bug
It's not obvious how to navigate to the Home page once viewing content in one of the four categories.

Originally filed as [FLOE-511](https://issues.fluidproject.org/browse/FLOE-511)

**Comment by jhung** [comment]
This issue will be addressed with #54.

**Comment by jobara** [comment]
Depends on #54
