### ISSUE TITLE
Articles on the Design Guide should appear in alphabetical order when listed

### ISSUE THREAD

**Issue by jhung** [inclusive-design/guide.inclusivedesign.ca#69]
## Describe the bug
When listing articles on the Design Guide, the articles should appear in alphabetical order.

Originally filed as [FLOE-485](https://issues.fluidproject.org/browse/FLOE-485)

## Additional context or notes
Some issues to consider:
* Should ordering be based on their short or long title if both are available, but have different starting letters?
* If alphabetical order is the convention, if article content has a list of links to other articles in the Guide, those should be alphabetically ordered as well.

**Comment by jhung** [comment]
There might be a way to effectively handle this using 11ty.

**Comment by jobara** [comment]
Can be addressed with #54
